### ISSUE TITLE
`isMounted()` does not work as described in README

### ISSUE THREAD

**Issue by dminkovsky** [rauldeheer/use-async-effect#16]
In the README it says:

> The async callback will receive a single function to check whether the component is still mounted:

When I first read this, I thought wow, that is very useful. Unfortunately, it does not work as I understood:

* The way I understood it, and thought would be useful, `isMounted()` returns `false` if the component has unmounted.
* The way it's implemented, the function will return `false` is the effect has been cleaned up due to a dependency change.

These are quite different, and I think the first variant is the actually useful one, specifically for:

* Avoiding updating state after unmount.
* Avoiding touching HTML node references that have been removed.

Given how `isMounted()` currently works, I'm not sure why it's useful.

Would it be possible to fix this? It would be a pretty simple PR I could submit, I think. Only thing would be a major version bump due to breaking change.

Thank you.

**Comment by dminkovsky** [comment]
I am thinking something like https://github.com/dminkovsky/use-async-effect/commit/aed005f42167aeea49f26bf76b121bf35b13e89d.

Alternatively, to make it a non-breaking change, `effect` could be passed-in a second function.

**Comment by dminkovsky** [comment]
Actually... having worked through this, I think I now understand why the code is written the way it is. The user may want to know whether dependencies have changed and the effect is being re-run, and that can only easily be determined from inside the hook. So maybe `isMounted()` should just be renamed to `didCleanUp()` or something? The naming is confusing/incorrect, at least with respect to the component. Keeping track of component mount state and providing it as in my patch above would be useful, but that can always be done by the user.

**Comment by gaberogan** [comment]
I agree it'd be more useful if this were changed, but it's a breaking change so I don't see that happening. For that reason, I would recommend probably writing a custom hook or wrapping this hook such that you do get the right value. For example:

```js
const useAsyncEffect = (effect, ...etc) => {
  const mounted = useMounted() // whatever implementation of this you like
  useAsyncEffectLib(() => {
    effect(mounted)
  }, ...etc)
}
```

**Comment by franciscop-sc** [comment]
> Given how isMounted() currently works, I'm not sure why it's useful.

It's the only way I found it useful after much testing (original author of the PR here). I agree the name is not the best, instead of isMounted it'd be technically `isFunctionStillMounted()`, `isActive()`, `isFresh()` or similar; it checks whether the currently running function is still active or not; it can become stale if the component is unmounted, or if the dependencies were changed and thus a new callback has been created, making the current/old one stale.

> These are quite different, and I think the first variant is the actually useful one, specifically for:
>   Avoiding updating state after unmount.
>   Avoiding touching HTML node references that have been removed.

It is _very_ useful in these cases! Like, the other way would actually be catastrophic. I'm going to give an example where the current implementation is the only valid way, not actually checking whether it's mounted or not:

```js
const [list, setList] = useState(null);
useAsyncEffect(async isMounted => {
  const data = await fetchFromApi(page);
  if (!isMounted()) return;
  setList(data);
}, [page]);
```

In here, if we don't check for isMounted we have a network run condition. Imagine pagination on a website, and we click the "next" few times quickly in a row. We need to make sure that when the async function has resolved, _that_ is the active function being rendered right now. Otherwise, if the first network call takes longer than the second one, it'd overwrite it giving us stale data in our component. If you only had access to a function checking if it's mounted or not, you would not be able to do this.

> Avoiding touching HTML node references that have been removed.

Could you provide an example for that please? All the cases I can think when I'm doing node references are sync, not async, and so I'd use `useEffect()` instead of `useAsyncEffect()`.
